
# Dependencies
markdown:         kramdown
highlighter:      pygments

# Basics
pygments:         true
lsi:              false
permalink:        pretty
  
# Setup
title:            tel.github.io
# tagline:          '$'
# description:      '$'
url:              http://tel.github.io
paginate:         10

author:
  name:           'Joseph Abrahamson'
  url:            https://twitter.com/sdbo

github:
  repo:           https://github.com/tel/tel.github.io


exclude:
  - vendor